set(CMAKE_SYSTEM_PROCESSOR x86)
set(TOOLCHAIN_ARCH x86)
set(CMAKE_C_COMPILER_TARGET   i386-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET i386-pc-windows-msvc)
include("${CMAKE_CURRENT_LIST_DIR}/msvc-wine-clang-cl.cmake")
